### ISSUE TITLE
Feature request: supporting placeholders in ProcessingStep constructor

### ISSUE THREAD

**Issue by lucaboulard** [aws/aws-step-functions-data-science-sdk-python#139]
Currently, the `container_arguments` parameter to the `ProcessingStep` constructor does not support placeholders, so that the only way to pass dynamic values to a processing job is to use a lambda to create a file on s3 with the values in it and bring it into the job as a processing input. Unfortunately this is quite inconvenient.
It would be a major improvement if `ProcessingStep`'s constructor accepted placeholders.

**Comment by ca-nguyen** [comment]
The fix (#155) will be available with next release

**Comment by yanhong-zhao-ef** [comment]
I am wondering if we can re-open this issue since the original feature request is still not possible where execution_input['argument'].to_jsonpath() will get passed straight to the processing script without the variable being replaced on execution and execution_input['argument'] runs into TypeError: Object of type ExecutionInput is not JSON serializable when trying to create workflow
